"use client";

/**
 * LocaleContext.tsx — App Shell Locale State
 *
 * ARCHITECTURE RULES:
 *  ✅ Locale controlled by React state only (no auto-detection)
 *  ✅ Persisted to localStorage via persistLocale()
 *  ✅ Initialized from localStorage on first render
 *  ✅ t(key) resolves namespaced dot-path keys from locale JSON
 *  ✅ No RTL logic (removed by design)
 *  ✅ No mixing of GenUI content with lingo translations
 *
 * When locale changes:
 *  1. React state updates → all shell components re-render with new strings
 *  2. localStorage updated → survives page refresh
 *  3. LOCALE_CHANGE_EVENT dispatched → C1 GenUI regenerates in new language
 */

import React, {
    createContext,
    useContext,
    useState,
    useCallback,
    useEffect,
} from "react";
import {
    persistLocale,
    loadPersistedLocale,
    I18N_CONFIG,
} from "@/i18n/lingo";
import { translate, type Locale, SUPPORTED_LOCALES } from "@/app/utils/translate";

// ─── Custom Event for GenUI Regeneration ──────────────────────────────────────

/**
 * Dispatched whenever the user changes locale.
 * C1 shape components listen for this to regenerate their content.
 * GenUI is NEVER translated via lingo — it regenerates from scratch.
 */
export const LOCALE_CHANGE_EVENT = "app:locale-change";

export function dispatchLocaleChange(locale: Locale): void {
    if (typeof window !== "undefined") {
        window.dispatchEvent(
            new CustomEvent<{ locale: Locale }>(LOCALE_CHANGE_EVENT, {
                detail: { locale },
            })
        );
    }
}

// ─── Context Type ─────────────────────────────────────────────────────────────

interface LocaleContextValue {
    /** Currently active locale code */
    locale: Locale;
    /**
     * Switch locale — persists to localStorage + fires LOCALE_CHANGE_EVENT
     * for C1 GenUI regeneration. Never triggers auto-detection.
     */
    setLocale: (locale: Locale) => void;
    /**
     * Translate an app-shell key (dot-path notation).
     * @example t("toolbar.undo") → "Undo" (en), "Rückgängig" (de)
     * @example t("modal.confirmDelete.title") → "Delete Component"
     *
     * NEVER use this on GenUI content.
     */
    t: (key: string) => string;
    /** All supported locales for rendering the language selector */
    supportedLocales: { code: Locale; label: string; nativeLabel: string }[];
}

// ─── Context ──────────────────────────────────────────────────────────────────

const LocaleContext = createContext<LocaleContextValue>({
    locale: I18N_CONFIG.defaultLocale,
    setLocale: () => { },
    t: (key) => key,
    supportedLocales: SUPPORTED_LOCALES,
});

// ─── Provider ─────────────────────────────────────────────────────────────────

export function LocaleProvider({ children }: { children: React.ReactNode }) {
    // Initialise from localStorage (synchronously on client; SSR gets default)
    const [locale, setLocaleState] = useState<Locale>(I18N_CONFIG.defaultLocale);

    // Hydrate from localStorage after mount (avoids SSR mismatch)
    useEffect(() => {
        const persisted = loadPersistedLocale();
        if (persisted !== locale) {
            setLocaleState(persisted);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const setLocale = useCallback((newLocale: Locale) => {
        setLocaleState(newLocale);
        persistLocale(newLocale);
        // Fire event so C1 GenUI shapes can regenerate in the new language.
        // GenUI content is NOT translated — it is regenerated by C1.
        dispatchLocaleChange(newLocale);
    }, []);

    // Update html lang attribute on locale change
    useEffect(() => {
        if (typeof document !== "undefined") {
            document.documentElement.lang = locale;
        }
    }, [locale]);

    const t = useCallback(
        (key: string) => translate(key, locale),
        [locale]
    );

    return (
        <LocaleContext.Provider
            value={{ locale, setLocale, t, supportedLocales: SUPPORTED_LOCALES }}
        >
            {children}
        </LocaleContext.Provider>
    );
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

/**
 * useLocale — access App Shell i18n state.
 *
 * @example
 * const { t, locale, setLocale } = useLocale();
 * <button>{t("button.save")}</button>
 * <select onChange={e => setLocale(e.target.value as Locale)} />
 */
export function useLocale(): LocaleContextValue {
    return useContext(LocaleContext);
}
